### ISSUE TITLE
Need documentation 

### ISSUE THREAD

**Issue by uitlaber** [apstanisic/directus-dart#1]

**Comment by apstanisic** [comment]
It will be written before reaching stable, I need to finalize api first

**Comment by uitlaber** [comment]
You have any todo - list ?

**Comment by apstanisic** [comment]
I'm still in process of porting js sdk. Dart type system is not flexible like ts, so for most of params there needs to be specific class. And then I need to write tests.

**Comment by apstanisic** [comment]
There is documentation in [README](https://github.com/apstanisic/directus-dart/blob/main/README.md), and API documentation for every version [here](https://pub.dev/packages/directus/versions). 
SDK is not stable, and currently only works with `Directus.custom` static method that requires `Dio` instance, and Storage that extends `DirectusStorage`.
For now it's best to use fixed version: `directus: 0.2.0` in `pubspec.yml`
Documentation will be updated for every minor version, but there will be breaking changes in patch versions.
After 1.0.0, package will follow semver.
I still have to decide on what storage package to use, and lots of APIs are gonna change, but if anyone wants to play with it, it should work
