### ISSUE TITLE
Transform the Directus class into Singleton

### ISSUE THREAD

**Issue by kellvembarbosa** [apstanisic/directus-dart#12]
Hello, first I would like to thank you for the package, it is very useful and well built!

I would like to know if there is a special reason for not using the 'Directus' class as a singleton, so I would keep the same instance to be recovered anywhere in the application.

I did a singleton on a project that I used your package to analyze and see if it would be interesting for the package.

The interesting thing about working with a singleton is that it would be possible to recover the same instance globally.

https://github.com/kellvembarbosa/directus-dart

**Comment by apstanisic** [comment]
It's a cool idea, but that would limit SDK to single API endpoint because user could not have more APIs at the same point.
It could be cool to be used in addition to current API, something like

```dart
await Directus.initSingleton(url);
final sdk = Directus.getInstance();
```
Or even better, seperate class. This way this does not add complexity to existing Directus class, and would be easier to test.
```dart
await DirectusInstance.init(url);
final sdk = DirectusInstance();
````

**Comment by kellvembarbosa** [comment]
the second option is very interesting!  you would not need to change the current Directus class, and the DirectusInstance class will only be for those who want a singleton, so maintenance will be minimal...

**Comment by apstanisic** [comment]
Yeah, 2nd looks better. Can you port commits from [https://github.com/kellvembarbosa/directus-dart](https://github.com/kellvembarbosa/directus-dart) to look like second option, and open PR?

**Comment by kellvembarbosa** [comment]
I'm going to do this, I'm just sorry for the delay my week is being very hectic due to the new confinement in Portugal...

**Comment by apstanisic** [comment]
Sure, whenever you have free time!

**Comment by kellvembarbosa** [comment]
Hi,

I made the commit could you see and tell me what you think of this implementation or give any improvement tips before doing the PR?

**Comment by apstanisic** [comment]
Looks good! Just some small tweaks. Open a PR so I can comment on code
