### ISSUE TITLE
How add  header for Directus client 

### ISSUE THREAD

**Issue by uitlaber** [apstanisic/directus-dart#15]
I need every request add header device_code. Is it possible?

**Comment by apstanisic** [comment]
This will set header for shared instance. `sdk.custom` is simply Dio client that was intended for custom endpoints. In next version I'll make `sdk.client` public.
```dart
sdk.custom.options.headers['Custom-Header'] = 'some-value';
```

**Comment by apstanisic** [comment]
From 0.5.1 you have access to `sdk.client` where you have full access to Dio client that is used
