### ISSUE TITLE
Cannot use on flutter 2.2.3 and MacOS

### ISSUE THREAD

**Issue by bahamut657** [apstanisic/directus-dart#19]
Hi
I'm trying to use your library to communicate with my Directus installation.

Flutter version: 2.2.3
OS: MacOS 11.2.3

Running your main.dart code, inside the example folder in this project I obtain this, upon running:
`Restarted application in 845ms.
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
#0      MethodChannel.binaryMessenger
package:flutter/…/services/platform_channel.dart:142
#1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:148
#2      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:331
#3      MethodChannel.invokeMapMethod
package:flutter/…/services/platform_channel.dart:358
#4      MethodChannelSharedPreferencesStore.getAll
package:shared_preferences_platform_interface/method_channel_shared_preferences.dart:44
#5      SharedPreferences._getSharedPreferencesMap
package:shared_preferences/shared_preferences.dart:180
#6      SharedPreferences.getInstance
package:shared_preferences/shared_preferences.dart:56
#7      SharedPreferencesStorage.getItem
package:directus/…/adapters/shared_preferences_storage.dart:14
#8      AuthStorage.getLoginData
package:directus/…/auth/_auth_storage.dart:29
#9      AuthHandler.init
package:directus/…/auth/auth_handler.dart:82
#10     Directus.init
package:directus/src/directus.dart:56
#11     main
package:redux_saga_beginner_tutorial/main.dart:8
#12     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
#13     _rootRun (dart:async/zone.dart:1354:13)
#14     _CustomZone.run (dart:async/zone.dart:1258:19)
#15     _runZoned (dart:async/zone.dart:1789:10)
#16     runZonedGuarded (dart:async/zone.dart:1777:12)
#17     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
#18     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
`

How to resolve this problem? Am I missing something?
Regards

**Comment by marcusfelix** [comment]
> Are you cloning the repo and running project in the `example` folder, or using it in your project with `pubspec.yaml`?
> 
> I don't have macOS to reproduce, does it also happen on other platforms?

I can confirm that error happen on iOS with Flutter Channel master, 2.6.0-1.0.pre.86

**Comment by apstanisic** [comment]
Can you call `WidgetsFlutterBinding.ensureInitialized();` before initializing SDK? 
It looks like it's regression in Flutter: https://github.com/flutter/flutter/issues/78028

I'll create PR soon that calls this method internally.
It looks like this is the same exception [this](https://stackoverflow.com/a/68178721), https://github.com/flutter/flutter/issues/80956

**Comment by apstanisic** [comment]
Version `0.6.2` is published that should fix this issue

**Comment by bahamut657** [comment]
I can confirm that version 0.6.2 resolves the issue. Now this library is working well on MacOS and Web. 
Thank you so much for the work done
Regards
