### ISSUE TITLE
Offer a pure dart package

### ISSUE THREAD

**Issue by ngjoni** [apstanisic/directus-dart#23]
It would be awesome if this package could also be offered as a plain dart package. For example you can create your own packages in flutter and define there your API with this package and keeping the flutter root directory pristine.

**Comment by apstanisic** [comment]
It shouldn't be hard, since only reason that there is a Flutter dependency is because package uses shared preferences. We already accept any compatible storage in constructor, so it's just extracting core to another package.

If anyone knowns about how monorepo function in dart/flutter, I'm open for PR

**Comment by workatease** [comment]
why dont we move to [hive](https://pub.dev/packages/hive) instead of shared preference
this will remove the dependency on flutter

**Comment by apstanisic** [comment]
We don't know where we can save data without Flutter. For that reason there are separate packages for hive: `hive` and `hive_flutter`. [See hive docs](https://docs.hivedb.dev/#/basics/hive_in_flutter).

It's all about convenience. We can either use some storage for Flutter, or use any generic storage but require user install additional package and manually provide path.

So I choose this:
```dart
import 'package:directus/directus.dart';

final sdk = await Directus('http://localhost:8055').init();
```
over something like this:
```dart
import 'package:directus/directus.dart';
import 'package:path_provider/path_provider.dart';

var appDir = await getApplicationDocumentsDirectory();
final sdk = await Directus('http://localhost:8055', appDir).init();
```

**Comment by apstanisic** [comment]
There is now `directus_core` package that does not require Flutter
