### ISSUE TITLE
Static Token usage is not available 

### ISSUE THREAD

**Issue by workatease** [apstanisic/directus-dart#24]
I was looking for Auth using static token . but sure it is supported yet

**Comment by apstanisic** [comment]
Is that a feature that Directus supports? Can you link me to the docs?

**Comment by apstanisic** [comment]
It does. It should be easy to implement with dio interceptors.

**Comment by apstanisic** [comment]
It's available in the main branch. It can be called with `sdk.auth.staticToken('token')`. I need to write documentation and fix some failing test before publishing new version.
If you need to use this feature now, you can just set main branch is `pubspec.yaml`. [Dart Docs](https://dart.dev/tools/pub/dependencies#git-packages).

**Comment by apstanisic** [comment]
Published 0.7.0, please reopen issue if there are problems
