### ISSUE TITLE
Unable to use typedItems

### ISSUE THREAD

**Issue by awesome-developer-20** [apstanisic/directus-dart#33]
I am not able to use typedItems in my application.

typedItems need a converter of type ItemsConverter which I can't import. Dart gives me warning when importing files from src folder.

Can you please add `import 'package:directus/src/modules/items/items_converter.dart';` to directus.dart outside src folder? It would be really helpful.

By the way, thanks for such a helpful library 🙂

**Comment by awesome-developer-20** [comment]
I've created custom ItemsConverter for my data models but dart is showing warings on directus/src imports

![image](https://user-images.githubusercontent.com/84862109/154852823-9ff1ad34-41df-4a40-9a8d-a24a4cb9dd88.png)

**Comment by apstanisic** [comment]
I'll check it out.

**Comment by apstanisic** [comment]
Can you check if this problem still persists. It works for me in 0.9.2

Here is working example bellow. Please reopen if error still persist
```dart
import 'package:directus/directus.dart';

class Article {
  int id;
  Article(this.id);
}

class ConverterNew extends ItemsConverter<Article> {
  @override
  Article fromJson(Map<String, Object?> data) {
    return Article(data['id'] as int);
  }

  @override
  Map<String, Object?> toJson(Article data) {
    return {"id": data.id};
  }
}

void main() async {
  final sdk = await Directus('http://localhost:8055').init();
  final results =
      await sdk.typedItems('articles', converter: ConverterNew()).readOne('1');
  // ignore: avoid_print
  print(results);
}

```

**Comment by martin-braun** [comment]
@apstanisic #79 We also missing the ItemsHandler.
