### ISSUE TITLE
Not working with Dio 4.0.4

### ISSUE THREAD

**Issue by awesome-developer-20** [apstanisic/directus-dart#34]
Dio client is stuck at sending request when using 4.0.4 version. If I remove first interceptor (`DirectusSingleton.instance.client.interceptors.removeAt(0);`) it works properly. I don't know why 😕 

It is working fine with Dio 4.0.0

Maybe there is a breaking change in Dio interceptor api

**Comment by awesome-developer-20** [comment]
Maybe you have to add `return handler.next(options)` at the end here

![image](https://user-images.githubusercontent.com/84862109/154853322-26545f9b-afe6-40ab-8bab-e0aa5042f962.png)

Like this

![image](https://user-images.githubusercontent.com/84862109/154853368-e212ce87-bb91-4540-833b-053bed470890.png)

**Comment by apstanisic** [comment]
I think you're right. Dio changed their API and I didn't migrate properly in every place. Can you test if it works and send a PR?

**Comment by apstanisic** [comment]
I've published 0.7.1. Can you check if it fixes the issue?

**Comment by apstanisic** [comment]
Please reopen if issue is not fixed
