### ISSUE TITLE
Cannot log out

### ISSUE THREAD

**Issue by MichalNemec** [apstanisic/directus-dart#40]
Hello, im trying your library, looks good and clean so far, but i met an issue.
Login is without a problem.
Logout has some troubles
```
calling this in service
Future<dynamic> logout() async {
    Directus sdk = await Directus(API_ENDPOINT).init();
    return await sdk.auth.logout();
  }
```
in directus
```
22:06:09 Γ£¿ request completed POST 401 /auth/refresh 7ms
```
im checking in main.dart if `authEndpoint.isLoggedIn()` is false

but its true all the time.

seems like Authstorage `removeLoginData` isnt cleared.

**Comment by MichalNemec** [comment]
fixed by forking library and adding `await storage.removeLoginData(); ` inside logout final.

**Comment by apstanisic** [comment]
Thanks for reporting. Can you create PR?
