### ISSUE TITLE
await sdk.auth.logout() not working

### ISSUE THREAD

**Issue by reev-create** [apstanisic/directus-dart#43]
The sdk.auth.logout() does not log out from the local authenticated user. 

Once I use the logout() method and re-open the app, the previous user stays logged in :/

**Comment by apstanisic** [comment]
I think it's fixed in the df015ca7817c629a084d16a9f94084a7b371e643, And that the problem is that I still haven't publish new version on pub

**Comment by reev-create** [comment]
> I think it's fixed in the df015ca7817c629a084d16a9f94084a7b371e643, And that the problem is that I still haven't publish new version on pub
> 

Ah! Thanks!

**Comment by reev-create** [comment]
Hey, how can I contribute to this repo? I have a few ideas in mind

**Comment by apstanisic** [comment]
Sure. Just first open the issue for features you want.

This package is simply wrapper around Directus REST API, 
so you can check [Directus docs](https://docs.directus.io/reference/introduction/) to see if there is some feature that you want
