### ISSUE TITLE
Feature Request: works with firebase authentication natively

### ISSUE THREAD

**Issue by reev-create** [apstanisic/directus-dart#46]
I've seen someone create an extension for the web panel and the backend, would love to see flutter firebase auth provider to work with this sdk.

**Comment by apstanisic** [comment]
Can you provide some links? I'm not sure how and why would we connect this sdk with firebase. Directus has it's own auth

**Comment by reev-create** [comment]
> Can you provide some links? I'm not sure how and why would we connect this sdk with firebase. Directus has it's own auth

Firebase authentication or other authentication providers provide more methods like phone auth, apple id auth, etc.

**Comment by apstanisic** [comment]
This has to be done on the server. Directus does not accept firebase auth
