### ISSUE TITLE
Feature Request: making this package offline persistent natively

### ISSUE THREAD

**Issue by reev-create** [apstanisic/directus-dart#47]
If this package could natively enable/disable the persistent storage of data (caching the loaded data for offline usage) then it would change the game. (Just like firebase :3)

**Comment by apstanisic** [comment]
You can pass storage as constructor param. You need to extend DirectusStorage class. and pass it's instance to constructor
Example: 
```dart
// This way we will store data in this custom storage, that can be in memory
Directus('http://localhost', storage: someStorageInstance);
```
