### ISSUE TITLE
while uploadFile(filePath) it gets uploaded but some parsing error

### ISSUE THREAD

**Issue by reev-create** [apstanisic/directus-dart#48]
Getting this error ⬇️
`type 'String' is not a subtype of type 'int?' in type cast`
 while uploading file via 'uploadFile' method but it successfully uploads but throws error while parsing the response

**Comment by reev-create** [comment]
mostly occurring from the filesize field type as the server sends it as a String? but package defines it as int?

[https://github.com/apstanisic/directus-dart/blob/ec87f59f5260470a06f9672dddc1baf962a8b85d/lib/src/modules/files/directus_file.dart#L46](url)

**Comment by reev-create** [comment]
Auto detect content type and send the type as a MediaType object.

Hey, it would be great if I could also contribute to this repo.

**Comment by apstanisic** [comment]
It should return int for file size based on [Directus docs](https://docs.directus.io/reference/files/#the-file-object=)

**Comment by apstanisic** [comment]
Should be fixed, please try latest version. Reopen if exception still exists
