### ISSUE TITLE
Solution: createMany() throws an error "Problem with Directus". 

### ISSUE THREAD

**Issue by reev-create** [apstanisic/directus-dart#52]
The below line throws an error: "Problem with Directus"
https://github.com/apstanisic/directus-dart/blob/0bc0443fbf1a8ec4a0bb9038eaff520987131dec/lib/src/modules/items/items_handler.dart#L98

It should actually be converted to list like below
`final mapData = data.map((item) => converter.toJson(item)).toList();`

**Comment by apstanisic** [comment]
Can you open a PR?

**Comment by apstanisic** [comment]
Added your fix. Please try version 0.9.0, and reopen if problem persist
