### ISSUE TITLE
refresh token interceptor bug fix

### ISSUE THREAD

**Issue by azharul-islam** [apstanisic/directus-dart#59]
final response = await manuallyRefresh();
      if (response?.accessToken != null) {
        options.headers['authorization'] = 'Bearer ${response!.accessToken}';
      } else {
        options.headers.remove('authorization');
      }

Refresh token interceptor wasn't working. After changing "Authorization" to "authorization" and prepending "Bearer " fixed the issue.

**Comment by apstanisic** [comment]
I think the problem is not in upper case, but in `Bearer` part. In their [docs](https://docs.directus.io/reference/authentication.html#access-tokens), they are using uppercase `Authorization`.

Can  you test with only `Bearer ` added, and create PR?

**Comment by apstanisic** [comment]
Please try version 0.9.0, and reopen if problem persist
