### ISSUE TITLE
Auth Refresh fails and soft locks users out of the system

### ISSUE THREAD

**Issue by NickoftheSouth** [apstanisic/directus-dart#61]
# Expected Behaviour
When logging back into an app after a refresh token has expired login should work correctly. The user should then be authenticated and be able to access data according to their role.
In the case of a renewal token that has expired, I'd expect the SDK to attempt to login using the usual method at the `auth/login` endpoint.

# Current Behavior
When logging back into an app after a refresh token has expired login get's suck and the user is no longer able to log in at all. Even after calling:
```dart
sdk.auth.storage.removeLoginData();
```

# Steps to Reproduce
* Set up your Directus instance to have an auth token expire quickly
for example:
```ini
ACCESS_TOKEN_TTL=1m
REFRESH_TOKEN_TTL=2m
```
* Use the SDK to log into your system using valid credentials:
```dart
sdk.auth.login(email: email, password: password)
```
* Once you've logged in kill the app
* Wait for 3 minutes, or enough time for the tokens to expire
* Try to log in again in the same app

note: clearing out the data from the app fixes the issue.

# Context
Building machine: Windows 10

Flutter Doctor output:
```bash
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [Version 10.0.19045.2486], locale en-NZ)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.2)   
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.74.3)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!
```

directus sdk version: 0.9.3

# Detailed Description
Our testers have noticed that occasionally when trying to log in they'll get locked out of the app and we've worked out it's when the SDK is trying to use an expired renewal token. Since the default renewal token expiry is 7 days this only happens occasionally (until we set the expiry to much shorter).
Looks like the stored token is continued to be attempted and the login never reverts to the normal login methods, even after trying to clear out the stored user auth data.

**Comment by NickoftheSouth** [comment]
@apstanisic Yes I've tried logging off and now this update does not fix the issue.

I've had a deeper dig into the code and the issue is centered around the 
`refreshExpiredTokenInterceptor` method/callback in `auth_handler.dart`

This is called on all network calls.

The fix above adds in a check on failure (for example when the refresh token expires) and attempts to log out, which calls the above and attempts to `auth/refresh` which then fails and tries to log out, repeating forever.

By adding this line above the current fix:
```dart
tokens == null;
```

Stops the above infinite loop, but doesn't address the root issue. 
What I'd expect is if I'm calling `login()` with an email and password it should just work regardless of token or refresh token status.

that is if logging in fails, then it should automatically clear out the stored, problematic data, and attempt to log in again from scratch.


I can see from network monitoring that if there are stored tokens, the `auth/login` is never hit, only `auth/refresh` (which continues to fail since the refresh token has expired).

Am I missing some core security consideration or is this the expected behavior?

So here's what I did to fix this;

in the `login` function of `auth_handeler.dart`

I expanded the catch to automatically clear out the current tokens and try again with this:

```dart
 } catch (e) {
      if(tokens != null){
        tokens = null;
        return login(email: email, password: password, otp: otp);
      }
      throw DirectusError.fromDio(e);
    }
```

This seems to work as I'd expected, but I'm not sure if it introduces any additional security holes.

**Comment by apstanisic** [comment]
Yeah, I thought to reuse `login` method, but it's not possible, since it causes loop, and `_refreshClient` is locked.
You fix is good, just need to remove remaining properties. 

Can you try 0.9.5. This fix should delete all stored data on fail without trying to logout, and delete it just in case before trying to login like in your example

**Comment by NickoftheSouth** [comment]
@apstanisic Yep looks like `0.9.5` sorts the issue for me.

Thank you!
