### ISSUE TITLE
Deep Filter for translations

### ISSUE THREAD

**Issue by svoelz** [apstanisic/directus-dart#63]
Hello,

I am trying to deep filter my query like this deep[translations][_filter][languages_code][_eq]="en-US".
Unfortunately, the deep query parameter has to be of Map<String, Query>.
Is there any possibility to filter my subquery/relation?

The data structure is as follows
product -> translations

I tried to use Filter.relation but it returns both languages_codes.

My code looks like this:
```dart
await directusSdk.items('product').readMany(
        query: Query(limit: 1, offset: 0, fields: ['sku', 'image', 'translations.*'] ),
        filters: Filters({'and': Filter.and([
          {'sku': Filter.eq(sku)},
          {'translations': Filter.relation('languages_code', Filter.eq(languageCode))}
        ])})
    );
```
Thank you for your help.
I am using the apstanisic/directus-dart version  0.9.5 and directus 9.23.1.

**Comment by apstanisic** [comment]
Hi,

I ran your example locally and this is resulting url that I got:
```
/items/product?filter[_and][0][sku][_eq]=hello&filter[_and][1][translations][languages_code][_eq]=en&fields=sku,image,translations.*&limit=1&offset=0
```
To me it looks correct. 
What do `deep` in your url mean?

Filter accepts `Object`, so in the worst case scenario,you can simply pass path directly, something like:

```dart
  await sdk.items('product').readMany(
          filters: Filters(
            {"[translations][_filter][languages_code][_eq]": 'en'},
          ),
);
```

Can you provide me full url query that you are trying to achieve?

**Comment by svoelz** [comment]
Hi, 
I try to get this result:
/items/product?fields[]=sku, image, translations.*&filter[sku][_eq]=xxx&filter[translations][languages_code][_eq]=en-US&deep[translations][_filter][languages_code][_eq]=en-US

The problem is, that with just filter (without deep) it returns two translations (de-DE and en-US) and not just (en-US). If I use the deep filter, it returns just en-US.

**Comment by apstanisic** [comment]
Oh, I see the problem.

For now, I'll try to push update that would allow you to use something like code bellow. I know it's not ideal, but it's a quick fix until proper implementation.

```dart
 final res = await sdk.items('product').readMany(
        query: Query(
// This params are passed directly to url
            customParams: {
              "deep[translations][_filter][languages_code][_eq]": "en"
            },
            limit: 1,
            offset: 0,
            fields: ['sku', 'image', 'translations.*']),
        filters: Filters({
          'and': Filter.and([
            {'sku': Filter.eq('hello')},
            {'translations': Filter.relation('languages_code', Filter.eq('en'))}
          ])
        }));
```

**Comment by apstanisic** [comment]
I publish v0.11, which should enable you to do this:
```dart
    final res = await sdk.items('product').readMany(
        query: Query(customParams: {
          "deep[translations][_filter][languages_code][_eq]": "en-US",
        }, fields: [
          'sku',
          'image',
          'translations.*'
        ]),
        filters: Filters({
          'sku': Filter.eq('hello'),
          'translations': Filter.relation(
            'languages_code',
            Filter.eq('en-US'),
          ),
        }));
```
This will generate this url: `/items/product?filter[sku][_eq]=hello&filter[translations][languages_code][_eq]=en-US&fields=sku,image,translations.*&deep[translations][_filter][languages_code][_eq]=en-US`.
I know it's ugly, but this is best I can do currently, without either introducing big breaking change or removing type safety for `Query`

**Comment by svoelz** [comment]
Hi, 
thank you. This works for me.

**Comment by oranorr** [comment]
Is there any way to ask deep query when requesting readOne method? 
for example, Entity A has 105 o2m ids relations of Entity B. By default I see that Directus requests only 100. I tried implementing something like

```
 Future<void> test() async {
    final res = await directus.readOne(
      collection: usersCollection,
      id: userBloc.state.user.directusId,
      query: Query(
        deep: {
          'days': Query(
            limit: 500,
          ), // увеличиваешь лимит конкретно для массива
        },
      ),
    );
    print(res['days'].last);
  }
```
But still I get 100th Id, not literally last one.
