### ISSUE TITLE
Broken link in code documentation

### ISSUE THREAD

**Issue by guyluz11** [apstanisic/directus-dart#66]
https://github.com/apstanisic/directus-dart/blob/8c2c8fb2d4a976211090c16cc892c0802bd19f76/packages/directus_core/lib/src/data_classes/filters.dart#L26

Broken link

![image](https://github.com/apstanisic/directus-dart/assets/9304740/89df09e6-0b1d-42d3-b2b0-9cec0fc33244)

**Comment by milansurelia** [comment]
Is this the right Link for Filter Documentation?

https://github.com/directus/directus/blob/main/docs/reference/filter-rules.md

**Comment by guyluz11** [comment]
> Is this the right Link for Filter Documentation? @guyluz11
> 
> https://github.com/directus/directus/blob/main/docs/reference/filter-rules.md

Not sure, if we are going only by file name it suppose to be this one
https://github.com/directus/directus/blob/main/docs/reference/files.md

**Comment by apstanisic** [comment]
I think @milansurelia is right. @guyluz11 Your link is pointing to files, not filter.

**Comment by milansurelia** [comment]
Sent a PR which with updated URL #70
