### ISSUE TITLE
Upgrade the packages to Dart 3.0

### ISSUE THREAD

**Issue by milansurelia** [apstanisic/directus-dart#68]
Since **Dart 3.0** has been announced, we can update this package to Dart 3.0. It will drastically improve the package code.
By using the new feature of Dart 3.0, we can trim down the lines of code we've written while making it more robust and error-prone.

**Comment by apstanisic** [comment]
I current do not have time to port it to Dart 3. I'm open for PRs

**Comment by apstanisic** [comment]
We should probably keep in mind that Directus supports custom fields on system collections, so we should probably find a pretty way to enable that feature #56
