### ISSUE TITLE
Why there is a Flutter Dependency in Directus Dart Package for shared_preferences?

### ISSUE THREAD

**Issue by milansurelia** [apstanisic/directus-dart#69]
The shared_preferences package is presently used by the Directus Dart package. But having a Flutter dependency in a Dart app seems uncommon. This bug seeks to explain the justification for using the Flutter dependency and investigate possible alternatives or modifications.

Could you please provide an explanation & example for the inclusion of the Flutter dependency in the Directus Dart package It would also be beneficial to investigate alternate strategies or improvements to eliminate the Flutter dependency while still enabling the shared_preferences capability in the Dart project.

**Comment by milansurelia** [comment]
If `directus` package is developed for improving DX for Flutter Developers, IMO We should add the example as a Flutter Project

Can we add the Flutter Example in `directus` package?

What's your thought on this? @apstanisic

**Comment by apstanisic** [comment]
Sure. PRs are welcome

**Comment by milansurelia** [comment]
@apstanisic  I have created a separate issue to track the addition of the Flutter example. #72
